name: CD-github-action

on: 
  push: 
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      FRONTEND_APP_NAME: "gitops-frontend"
      BACKEND_APP_NAME: "gitops-backend"

    steps:
      - uses: actions/checkout@v4

      - name: Generate tag
        run: |-
          TAG_NAME="v1.0.${{ github.run_number }}"

          echo "VERSION='${TAG_NAME}'" >> $GITHUB_ENV

      - name: Push gihub tag
        run: |-
          git config user.name ${{ secrets.ACTOR }}
          git config user.email ${{ secrets.ACTOR_EMAIL }}
          git tag "${VERSION}"
          git push --tag

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container frontend
        working-directory: ./frontend
        run: |-
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_APP_NAME }}:${VERSION}"

          docker build -f ./dockerfile -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"

      - name: Build and push container backend
        working-directory: ./backend
        run: |-
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_APP_NAME }}:${VERSION}"

          docker build -f ./dockerfile -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"